### PR TITLE
Fixes truffls#32: Added key prop to manager render

### LINKED ISSUE #32: Each child in a list should have a unique "key" prop
I am seeing following warning after adding this plugin:

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Styled(div)>. See https://fb.me/react-warning-keys for more information.
    in LocalePanel
    in Unknown
    in Unknown
    in Unknown
    in Unknown (created by Context.Consumer)
    in _default (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Panel)
    in Panel (created by Layout)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in div (created by Context.Consumer)
    in Styled(div) (created by Main)
    in Main (created by Layout)
    in Layout (created by Context.Consumer)
    in WithTheme(Layout) (created by ResizeDetector)
    in ResizeDetector
    in div (created by Context.Consumer)
    in Styled(div)
    in Unknown
    in Unknown (created by ResizeDetector)
    in ResizeDetector
    in Unknown
    in Unknown (created by Manager)
    in ThemeProvider (created by Manager)
    in Manager (created by Context.Consumer)
    in Location (created by QueryLocation)
    in QueryLocation (created by Root)
    in LocationProvider (created by Root)
    in HelmetProvider (created by Root)
    in Root
```

Seems that `LocalePanel` is part of this library?

### PR DESCRIPTION
**Pull request by vdh**
Fixes #32 by adding a key prop to the render, with added tests for key vs no key.

### CODE REVIEW

File: src/manager/index.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ export function register () {
             title: 'Locales',
             render: (props) => (
                 <LocalePanel
+                    key={props && typeof props === 'object' && props.key || undefined}
```
Comment (floriangosse) [inline src/manager/index.js]: What do you think about removing the first check `props`? Because it's already covered by the `typeof` check.

Comment (vdh) [reply src/manager/index.js]: @floriangosse It's a short circuit to avoid the ugly fact that `typeof null` is `object`

Comment (floriangosse) [reply src/manager/index.js]: Good point, hadn't this case in mind.
